version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    command: >
      sh -c "
        echo 'Waiting for Elasticsearch...';
        until curl --silent --fail http://elasticsearch:9200/_cluster/health?wait_for_status=yellow; do
          echo 'Elasticsearch not ready, waiting...';
          sleep 5;
        done;
        echo 'Elasticsearch is up!';
        npm run load-data &&
        npm run build &&
        npm start
      "

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl --silent --fail http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=20s || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  esdata:
